#!/bin/sh
export SCRIPTPATH
SCRIPTPATH="$( cd "$(dirname "$0")" || exit; pwd -P )"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s "$SCRIPTPATH"/down /tmp/leftwm-theme-down

# Boot picom or compton if it exists
picom --config "$SCRIPTPATH"/picom.conf &

# Set the theme.toml config
leftwm command "LoadTheme $SCRIPTPATH/theme.toml"

# Set background
 if [ -x "$(command -v feh)" ]; then
  feh --randomize --bg-fill "$SCRIPTPATH"/wallpapers/*
fi

dunst -conf "$SCRIPTPATH"/dunst/dunstrc &

playerctld daemon &

index=0
leftwm-state -q -n -t "$SCRIPTPATH"/polybar/sizes.liquid | sed -r '/^\s*$/d' | while read -r width
do
  barname="mainbar$index"
  monitor="$(polybar -m | awk -v i="$(( index + 1 ))" 'NR==i{print}' | sed s/:.*// | tr -d '\n')"
  monitor=$monitor width=$(( width - 16 )) polybar -c "$SCRIPTPATH"/polybar/config.ini $barname &
  index=$((index+1))
done
